### ISSUE TITLE
Research existing maze games

### ISSUE THREAD

**Issue by SAUCE-2** [SAUCE-2/Geiger#3]
Need to look at existing maze games and look at them from an educational standpoint.

**Comment by SAUCE-2** [comment]
https://knowledge-hub.com/2021/05/18/educational-benefits-of-solving-mazes-for-kids/
https://www.mdpi.com/2071-1050/14/11/6794
https://link.springer.com/chapter/10.1007/978-3-031-17601-2_9

Benefits to using maze games for education
- Enhances problem solving skills and critical thinking
- Improves spatial awareness
- Develops solution oriented approaches
- Builds patience and resilience
- Hands on learning
- Tests understanding through interactive elements (In our case its understanding that PPE will allow you to live and also that you need to get rid of nuclear waste)
- Simulates time-critical decision making (you die after 3 mins matey)

**Comment by JayDuuUK** [comment]
Where are the other maze games you looked at?
